version: 0.1

phases:
  install:
    commands:
      - echo Installing Gulp Tools... 
      - npm install gulp-cli gulp gulp-util gulp-less gulp-clean-css gulp-jade gulp-uglify gulp-concat pump path -g
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - gulp
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - templates/
    - app.js
    - HelloWorld.js
